/**
 * adapter-capabilities.generated — generated by scripts/generate-site-adapter-capabilities.mjs.
 *
 * Do not edit by hand. This is the public-site snapshot of what the adapter
 * registry says agent-connector installs today. Human-authored host-native
 * provenance stays in site/src/platform-data.ts.
 */

export type GeneratedParadigmId = "json-stdio" | "mcp-only" | "ts-plugin";

export type GeneratedSurfaceKey =
  | "mcp"
  | "hooks"
  | "commands"
  | "skills"
  | "subagents"
  | "memory"
  | "statusline"
  | "actions";

export interface GeneratedPlatformSurfaces {
  mcp: boolean;
  hooks: boolean;
  commands: boolean;
  skills: boolean;
  subagents: boolean;
  memory: boolean;
  statusline: boolean;
  actions: boolean;
}

export interface GeneratedAdapterCapabilityProfile {
  id: string;
  name: string;
  paradigm: GeneratedParadigmId;
  surfaces: GeneratedPlatformSurfaces;
}

export const generatedSurfaceKeys = [
  "mcp",
  "hooks",
  "commands",
  "skills",
  "subagents",
  "memory",
  "statusline",
  "actions"
] as const satisfies readonly GeneratedSurfaceKey[];

export const generatedSurfaceLabels: Record<GeneratedSurfaceKey, string> = {
  mcp: "MCP",
  hooks: "Hooks",
  commands: "Commands",
  skills: "Skills",
  subagents: "Subagents",
  memory: "Memory",
  statusline: "Statusline",
  actions: "Actions",
};

export const adapterCapabilityProfiles = [
  {
    "id": "codebuddy",
    "name": "CodeBuddy",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "claude-code",
    "name": "Claude Code",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": true,
      "actions": false
    }
  },
  {
    "id": "codex",
    "name": "Codex CLI",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "vscode-copilot",
    "name": "VS Code Copilot",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "copilot-cli",
    "name": "GitHub Copilot CLI",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "gemini-cli",
    "name": "Gemini CLI",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "warp",
    "name": "Warp",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "opencode",
    "name": "OpenCode",
    "paradigm": "ts-plugin",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "mimo-code",
    "name": "MiMoCode",
    "paradigm": "ts-plugin",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "kilo-cli",
    "name": "Kilo CLI",
    "paradigm": "ts-plugin",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "droid",
    "name": "Droid (Factory)",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "openhands",
    "name": "OpenHands",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": false,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "roo-code",
    "name": "Roo Code",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": true,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "kilo",
    "name": "Kilo Code",
    "paradigm": "ts-plugin",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "cline",
    "name": "Cline",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": true,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "trae",
    "name": "Trae",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "antigravity-cli",
    "name": "Antigravity CLI",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": true,
      "actions": false
    }
  },
  {
    "id": "antigravity",
    "name": "Google Antigravity",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "zed",
    "name": "Zed",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "amp",
    "name": "Amp",
    "paradigm": "ts-plugin",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "codebuff",
    "name": "Codebuff",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": false,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "mux",
    "name": "Mux",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "pi",
    "name": "Pi",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": false,
      "hooks": false,
      "commands": true,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "jetbrains-copilot",
    "name": "JetBrains Copilot",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "qwen-code",
    "name": "Qwen CLI",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": true,
      "actions": false
    }
  },
  {
    "id": "kiro",
    "name": "Kiro",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "kimi",
    "name": "Kimi CLI",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "crush",
    "name": "Crush",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "goose",
    "name": "Goose",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "hermes",
    "name": "Hermes Agent",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "omp",
    "name": "Oh My Pi (OMP)",
    "paradigm": "ts-plugin",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": false,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "nemoclaw",
    "name": "NVIDIA NemoClaw",
    "paradigm": "ts-plugin",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "openclaw",
    "name": "OpenClaw",
    "paradigm": "ts-plugin",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": true
    }
  },
  {
    "id": "amazon-q",
    "name": "Amazon Q Developer CLI",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": false,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "continue",
    "name": "Continue",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": false,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "windsurf",
    "name": "Windsurf",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": true,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "grok-build",
    "name": "Grok Build",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": true,
      "skills": true,
      "subagents": true,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "grok-cli",
    "name": "Grok CLI",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": false,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "devin",
    "name": "Devin CLI (Cognition)",
    "paradigm": "json-stdio",
    "surfaces": {
      "mcp": true,
      "hooks": true,
      "commands": false,
      "skills": true,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "open-interpreter",
    "name": "Open Interpreter",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": false,
      "skills": false,
      "subagents": false,
      "memory": false,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "junie",
    "name": "Junie",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": false,
      "skills": false,
      "subagents": false,
      "memory": true,
      "statusline": false,
      "actions": false
    }
  },
  {
    "id": "mistral-vibe",
    "name": "Mistral Vibe",
    "paradigm": "mcp-only",
    "surfaces": {
      "mcp": true,
      "hooks": false,
      "commands": false,
      "skills": false,
      "subagents": false,
      "memory": false,
      "statusline": false,
      "actions": false
    }
  }
] as const satisfies readonly GeneratedAdapterCapabilityProfile[];

export const adapterCapabilityCount = adapterCapabilityProfiles.length;
