/**
 * host-verification.generated — generated by scripts/generate-site-verification-results.mjs.
 *
 * Do not edit by hand. The source ledger is docs/host-verification-results.csv.
 */

export type VerificationLevelId = "e2e" | "live-runtime" | "live-accept" | "live-placement" | "install-doctor";

export interface HostVerificationResult {
  host: string;
  installProbe: string;
  doctorProbe: string;
  hostCliSurface: string;
  headlessModelMcpE2e: string;
  result: string;
  issueOrBlocker: string;
  evidence: string;
}

export const verificationLevelOrder = [
  "e2e",
  "live-runtime",
  "live-accept",
  "live-placement",
  "install-doctor",
] as const satisfies readonly VerificationLevelId[];

export const verificationLevelLabels: Record<VerificationLevelId, string> = {
  e2e: "E2E",
  "live-runtime": "Live runtime",
  "live-accept": "Live accept",
  "live-placement": "Live placement",
  "install-doctor": "Install + doctor",
};

export const verificationLevelDescriptions: Record<VerificationLevelId, string> = {
  e2e: "A real host advanced a model turn and the MCP tool call was observed.",
  "live-runtime": "A real host advanced a headless runtime and fired hooks or loaded MCP, but no model MCP tool-call E2E was observed.",
  "live-accept": "The host accepted or listed the installed MCP config, but auth or model access blocked the final turn.",
  "live-placement": "A real host CLI was installed and driven far enough to verify native placement plus uninstall cleanup, but no offline accept/runtime lane exists.",
  "install-doctor": "Placement, dry install, doctor, and uninstall hygiene are verified; no login-free headless runtime lane is available.",
};

export function verificationLevelForResult(result: string): VerificationLevelId {
  if (result === "VERIFIED_E2E") return "e2e";
  if (result === "LIVE_RUNTIME_VERIFIED") return "live-runtime";
  if (result === "MCP_INSTALL_VERIFIED_AUTH_BLOCKED") return "live-accept";
  if (result === "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE") return "live-placement";
  return "install-doctor";
}

export const hostVerificationResults = [
  {
    "host": "claude-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "claude 2.1.186 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_CLAUDE_E2E_OK; allowed MCP tool call reached notepad_stats"
  },
  {
    "host": "codebuddy",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE/extension host only in this environment",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "codex",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "codex-cli 0.142.0 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_CODEX_E2E_OK; MCP notepad_stats call observed"
  },
  {
    "host": "cursor",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "cursor-agent pinned Windows CLI installed in .verify-tools",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Cursor turn requires CURSOR_API_KEY before a model MCP tool-call",
    "evidence": "cursor-agent mcp list listed ac-verify; placement and uninstall clean passed"
  },
  {
    "host": "vscode-copilot",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "VS Code Copilot workspace/user config only",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_WITH_FIX",
    "issueOrBlocker": "user-scope hooks are workspace-scoped; patched to warn instead of writing project .github/hooks",
    "evidence": "after-fix OMAC registry install warns explicitly; OMAC repo stayed clean; adapter tests assert no .github/hooks write and doctor stays OK"
  },
  {
    "host": "jetbrains-copilot",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "JetBrains Copilot UI-managed MCP and .github workspace content",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_WITH_FIX",
    "issueOrBlocker": "user-scope install previously dirtied project .github; patched to warn/skip workspace-only hooks/content",
    "evidence": "after-fix OMAC registry install produced no repo dirt; adapter and install-roundtrip tests assert no user-scope native file writes"
  },
  {
    "host": "copilot-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "GitHub Copilot CLI 1.0.64 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_COPILOT_E2E_OK; MCP notepad_stats call observed"
  },
  {
    "host": "gemini-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "gemini 0.36.0 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Google returned UNSUPPORTED_CLIENT during model call",
    "evidence": "MCP connected; same Google lineage model+MCP path passed through Antigravity CLI"
  },
  {
    "host": "opencode",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "opencode 1.17.0 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_OPENCODE_E2E_OK"
  },
  {
    "host": "mimo-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "mimo @mimo-ai/cli installed in .verify-tools",
    "headlessModelMcpE2e": "PARTIAL",
    "result": "LIVE_RUNTIME_VERIFIED",
    "issueOrBlocker": "offline runtime fired hooks and MCP load passed, but the model turn did not call the MCP tool",
    "evidence": "mimo mcp list connected and server received initialize/tools/list; mimo run fired UserPromptSubmit, SessionStart, Stop; mcp-tool-call lane recorded no tools/call"
  },
  {
    "host": "kilo",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE/extension host only in this environment",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "kilo-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "kilo @kilocode/cli installed in .verify-tools",
    "headlessModelMcpE2e": "PARTIAL",
    "result": "LIVE_RUNTIME_VERIFIED",
    "issueOrBlocker": "offline runtime fired hooks, but no model MCP tool-call E2E was observed",
    "evidence": "kilo mcp list accepted config; kilo run fired events.log; placement and uninstall clean passed"
  },
  {
    "host": "warp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Warp terminal GUI host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "hermes",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no verified installable headless CLI package found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "npm hermes-cli is an unrelated travel-agency CLI, so it was not installed",
    "evidence": "identity guard skipped the wrong package; registry install+doctor probe remains the coverage floor"
  },
  {
    "host": "nemoclaw",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no verified installable headless CLI package found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "npm nemoclaw 0.1.0 has no bin and is identity-unverified",
    "evidence": "identity guard skipped the wrong package; registry install+doctor probe remains the coverage floor"
  },
  {
    "host": "openclaw",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "openclaw npm CLI installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no id-echoing offline accept verb; no login-free headless model tool-call lane",
    "evidence": "openclaw placement+uninstall clean passed; configSchema validate gap remains fixed"
  },
  {
    "host": "zed",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Zed editor config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "GUI/editor host; no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "antigravity",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Antigravity IDE config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE surface; CLI E2E is tracked under antigravity-cli",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "antigravity-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Antigravity CLI installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_AGY_E2E_OK; MCP_TOOL notepad_stats observed in transcript"
  },
  {
    "host": "kiro",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Kiro IDE config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "GUI/editor host; no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "qwen-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "qwen @qwen-code/qwen-code installed in .verify-tools",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Qwen CLI is auth-gated before a model MCP tool-call",
    "evidence": "qwen mcp list listed ac-verify; placement and uninstall clean passed"
  },
  {
    "host": "kimi",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "kimi @moonshot-ai/kimi-code 0.18.0 installed in .verify-tools",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Kimi model turn is auth-gated; offline doctor validates config only",
    "evidence": "kimi doctor config validated ac-verify config.toml; placement and uninstall clean passed"
  },
  {
    "host": "pi",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "pi @earendil-works/pi-coding-agent installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "content-only host; no MCP or lifecycle-hook accept/runtime lane",
    "evidence": "official Pi CLI installed; content fixture prompts/skills/actions/memory placement+uninstall clean passed"
  },
  {
    "host": "omp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "omp pinned Windows CLI installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline accept verb; omp -p is auth-gated with no offline model",
    "evidence": "omp placement+uninstall clean passed using pinned v16.0.10 Windows exe"
  },
  {
    "host": "droid",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "droid pinned Windows CLI installed in .verify-tools",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Droid model turn is auth-gated before a model MCP tool-call",
    "evidence": "droid mcp list listed ac-verify; placement and uninstall clean passed"
  },
  {
    "host": "openhands",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "openhands-ai package attempted; no app executable exposed by pipx install",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "package did not expose a local headless CLI app",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "roo-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Roo Code extension config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE/extension host only in this environment",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "cline",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "cline 3.0.29 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "INSTALL_DOCTOR_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "new Cline CLI requires account auth; current adapter targets VS Code extension settings, not ~/.cline CLI settings",
    "evidence": "cline headless run returned Unauthorized; extension-path doctor passed"
  },
  {
    "host": "trae",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "amp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "amp 0.0.1782236573-g268fa2 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "amp requires login/API key before model call",
    "evidence": "amp mcp list shows oh-my-agent-connector server configured"
  },
  {
    "host": "codebuff",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "codebuff npm CLI installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline accept verb; mcp list is parsed as an agent prompt and needs auth/runtime boot",
    "evidence": "codebuff placement+uninstall clean passed"
  },
  {
    "host": "mux",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "crush",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "crush @charmland/crush installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline accept verb; MCP lives in crush.json and model runtime needs provider setup",
    "evidence": "crush placement+uninstall clean passed after LOCALAPPDATA sandbox isolation"
  },
  {
    "host": "goose",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "goose pinned Windows CLI installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline accept verb; goose mcp takes a server name and mcp list is not a reader",
    "evidence": "goose v1.38.0 Windows zip downloaded; placement+uninstall clean passed"
  },
  {
    "host": "amazon-q",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Amazon Q CLI 1.19.7 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "q requires login before mcp list/chat model call",
    "evidence": "q mcp list and q chat --no-interactive return login required"
  },
  {
    "host": "continue",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Continue @continuedev/cli installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline config-accept verb; --mcp is an add-from-hub flag, not a reader",
    "evidence": "Continue placement+uninstall clean passed"
  },
  {
    "host": "windsurf",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Windsurf editor config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "GUI/editor host; no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "grok-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "grok-dev npm CLI installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline id-echoing accept verb verified; model turn is API-key/keychain gated",
    "evidence": "grok-cli placement+uninstall clean passed; npm install needs --legacy-peer-deps --engine-strict=false on Node v24.13.0"
  },
  {
    "host": "devin",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "host is remote/service-oriented; no login-free local headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "open-interpreter",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "interpreter installed through pipx",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "OpenAI-backed model path requires API key; free/local mode did not produce a usable stdin smoke response",
    "evidence": "interpreter CLI repaired after python3.12-dev plus setuptools injection; doctor passed"
  },
  {
    "host": "junie",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "junie @jetbrains/junie CLI installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline accept/list verb verified; no login-free headless model surface available",
    "evidence": "junie placement+uninstall clean passed"
  },
  {
    "host": "mistral-vibe",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "vibe pinned Windows CLI installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline accept/runtime lane verified; no login-free headless model surface available",
    "evidence": "Mistral Vibe v2.18.4 Windows zip downloaded; placement+uninstall clean passed"
  }
] as const satisfies readonly HostVerificationResult[];

export const hostVerificationCount = hostVerificationResults.length;
