/**
 * host-verification.generated — generated by scripts/generate-site-verification-results.mjs.
 *
 * Do not edit by hand. The source ledger is docs/host-verification-results.csv.
 */

export type VerificationLevelId = "e2e" | "live-accept" | "install-doctor";

export interface HostVerificationResult {
  host: string;
  installProbe: string;
  doctorProbe: string;
  hostCliSurface: string;
  headlessModelMcpE2e: string;
  result: string;
  issueOrBlocker: string;
  evidence: string;
}

export const verificationLevelOrder = [
  "e2e",
  "live-accept",
  "install-doctor",
] as const satisfies readonly VerificationLevelId[];

export const verificationLevelLabels: Record<VerificationLevelId, string> = {
  e2e: "E2E",
  "live-accept": "Live accept",
  "install-doctor": "Install + doctor",
};

export const verificationLevelDescriptions: Record<VerificationLevelId, string> = {
  e2e: "A real host advanced a model turn and the MCP tool call was observed.",
  "live-accept": "The host accepted or listed the installed MCP config, but auth or model access blocked the final turn.",
  "install-doctor": "Placement, dry install, doctor, and uninstall hygiene are verified; no login-free headless runtime lane is available.",
};

export function verificationLevelForResult(result: string): VerificationLevelId {
  if (result === "VERIFIED_E2E") return "e2e";
  if (result === "MCP_INSTALL_VERIFIED_AUTH_BLOCKED") return "live-accept";
  return "install-doctor";
}

export const hostVerificationResults = [
  {
    "host": "claude-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "claude 2.1.186 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_CLAUDE_E2E_OK; allowed MCP tool call reached notepad_stats"
  },
  {
    "host": "codebuddy",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE/extension host only in this environment",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "codex",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "codex-cli 0.142.0 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_CODEX_E2E_OK; MCP notepad_stats call observed"
  },
  {
    "host": "cursor",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Cursor config/probe only; no headless Cursor CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "Cursor user config/probe passed"
  },
  {
    "host": "vscode-copilot",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "VS Code Copilot workspace/user config only",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_WITH_FIX",
    "issueOrBlocker": "user-scope hooks are workspace-scoped; patched to warn instead of writing project .github/hooks",
    "evidence": "after-fix OMAC registry install warns explicitly; OMAC repo stayed clean; adapter tests assert no .github/hooks write and doctor stays OK"
  },
  {
    "host": "jetbrains-copilot",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "JetBrains Copilot UI-managed MCP and .github workspace content",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_WITH_FIX",
    "issueOrBlocker": "user-scope install previously dirtied project .github; patched to warn/skip workspace-only hooks/content",
    "evidence": "after-fix OMAC registry install produced no repo dirt; adapter and install-roundtrip tests assert no user-scope native file writes"
  },
  {
    "host": "copilot-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "GitHub Copilot CLI 1.0.64 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_COPILOT_E2E_OK; MCP notepad_stats call observed"
  },
  {
    "host": "gemini-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "gemini 0.36.0 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Google returned UNSUPPORTED_CLIENT during model call",
    "evidence": "MCP connected; same Google lineage model+MCP path passed through Antigravity CLI"
  },
  {
    "host": "opencode",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "opencode 1.17.0 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_OPENCODE_E2E_OK"
  },
  {
    "host": "mimo-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE/extension host only in this environment",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "kilo",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE/extension host only in this environment",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "kilo-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no installed/login-free Kilo CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "warp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Warp terminal GUI host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "hermes",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "nemoclaw",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "openclaw",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "zed",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Zed editor config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "GUI/editor host; no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "antigravity",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Antigravity IDE config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE surface; CLI E2E is tracked under antigravity-cli",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "antigravity-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Antigravity CLI installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_AGY_E2E_OK; MCP_TOOL notepad_stats observed in transcript"
  },
  {
    "host": "kiro",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Kiro IDE config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "GUI/editor host; no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "qwen-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "qwen 0.19.1 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Qwen CLI requires auth type selection before model call",
    "evidence": "qwen mcp list shows oh-my-agent-connector connected"
  },
  {
    "host": "kimi",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "pi",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "Pi file-based skills host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_WITH_FIX",
    "issueOrBlocker": "backupSettings tried to copy ~/.pi directory and produced EISDIR before fix; patched BaseAdapter to back up regular files only",
    "evidence": "after-fix OMAC registry install has no failedOn, no EISDIR, no backupSettings failure; pi regression test asserts backupSettings ignores ~/.pi directory"
  },
  {
    "host": "omp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "droid",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "openhands",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "openhands-ai package attempted; no app executable exposed by pipx install",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "package did not expose a local headless CLI app",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "roo-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Roo Code extension config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE/extension host only in this environment",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "cline",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "cline 3.0.29 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "INSTALL_DOCTOR_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "new Cline CLI requires account auth; current adapter targets VS Code extension settings, not ~/.cline CLI settings",
    "evidence": "cline headless run returned Unauthorized; extension-path doctor passed"
  },
  {
    "host": "trae",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "amp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "amp 0.0.1782236573-g268fa2 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "amp requires login/API key before model call",
    "evidence": "amp mcp list shows oh-my-agent-connector server configured"
  },
  {
    "host": "codebuff",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "codebuff 1.0.682 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "CLI opens TUI; no noninteractive headless completion flag found",
    "evidence": "version/help checked; registry doctor passed"
  },
  {
    "host": "mux",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "crush",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "crush v0.79.1 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "crush has no providers configured before model call",
    "evidence": "crush run reports provider setup required"
  },
  {
    "host": "goose",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "goose-ai command present but not a usable headless agent surface here",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "installed command output was not a usable MCP/model CLI path",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "amazon-q",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Amazon Q CLI 1.19.7 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "q requires login before mcp list/chat model call",
    "evidence": "q mcp list and q chat --no-interactive return login required"
  },
  {
    "host": "continue",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Continue config/probe only; continue command is shell builtin here",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no local headless Continue CLI available",
    "evidence": "Continue config/probe passed"
  },
  {
    "host": "windsurf",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Windsurf editor config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "GUI/editor host; no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "grok-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "grok CLI installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Grok CLI requires xAI API key/keychain before model call",
    "evidence": "grok prompts for API key"
  },
  {
    "host": "devin",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "host is remote/service-oriented; no login-free local headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "open-interpreter",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "interpreter installed through pipx",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "OpenAI-backed model path requires API key; free/local mode did not produce a usable stdin smoke response",
    "evidence": "interpreter CLI repaired after python3.12-dev plus setuptools injection; doctor passed"
  },
  {
    "host": "junie",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Junie IDE config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "IDE host; no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  },
  {
    "host": "mistral-vibe",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "no usable local headless CLI found",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED",
    "issueOrBlocker": "no login-free headless model surface available",
    "evidence": "registry install+doctor probe passed"
  }
] as const satisfies readonly HostVerificationResult[];

export const hostVerificationCount = hostVerificationResults.length;
