/**
 * host-verification.generated — generated by scripts/generate-site-verification-results.mjs.
 *
 * Do not edit by hand. The source ledger is docs/host-verification-results.csv.
 */

export type VerificationLevelId = "e2e" | "live-runtime" | "live-accept" | "live-placement" | "adapter-placement" | "install-doctor";

export interface HostVerificationResult {
  host: string;
  installProbe: string;
  doctorProbe: string;
  hostCliSurface: string;
  headlessModelMcpE2e: string;
  result: string;
  issueOrBlocker: string;
  evidence: string;
}

export const verificationLevelOrder = [
  "e2e",
  "live-runtime",
  "live-accept",
  "live-placement",
  "adapter-placement",
  "install-doctor",
] as const satisfies readonly VerificationLevelId[];

export const verificationLevelLabels: Record<VerificationLevelId, string> = {
  e2e: "E2E",
  "live-runtime": "Live runtime",
  "live-accept": "Live accept",
  "live-placement": "Live placement",
  "adapter-placement": "Adapter placement",
  "install-doctor": "Install + doctor",
};

export const verificationLevelDescriptions: Record<VerificationLevelId, string> = {
  e2e: "A real host advanced a model turn and the MCP tool call was observed.",
  "live-runtime": "A real host advanced a headless runtime and fired hooks or loaded MCP, but no model MCP tool-call E2E was observed.",
  "live-accept": "The host accepted or listed the installed MCP config, but auth or model access blocked the final turn.",
  "live-placement": "A real host CLI was installed and driven far enough to verify native placement plus uninstall cleanup, but no offline accept/runtime lane exists.",
  "adapter-placement": "No local host CLI can be driven, but the supported adapter was installed into an isolated HOME/project and cleanly uninstalled.",
  "install-doctor": "Placement, dry install, doctor, and uninstall hygiene are verified; no login-free headless runtime lane is available.",
};

export function verificationLevelForResult(result: string): VerificationLevelId {
  if (result === "VERIFIED_E2E") return "e2e";
  if (result === "LIVE_RUNTIME_VERIFIED") return "live-runtime";
  if (result === "MCP_INSTALL_VERIFIED_AUTH_BLOCKED") return "live-accept";
  if (result === "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE") return "live-placement";
  if (result === "ADAPTER_PLACEMENT_VERIFIED") return "adapter-placement";
  return "install-doctor";
}

export const hostVerificationResults = [
  {
    "host": "claude-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "claude 2.1.186 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_CLAUDE_E2E_OK; allowed MCP tool call reached notepad_stats"
  },
  {
    "host": "codebuddy",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "IDE/extension host; no local headless CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local host CLI accept/runtime lane; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "codex",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "codex-cli 0.142.0 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_CODEX_E2E_OK; MCP notepad_stats call observed; agent-plugin (Agent Plugins 1.0.0) SSOT bundle live-verified on codex-cli 0.149.0 macOS 2026-09-02: plugin marketplace add + plugin add + plugin list shows installed/enabled from the root plugin.json bundle"
  },
  {
    "host": "cursor",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "cursor-agent pinned Windows CLI installed in .verify-tools",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Cursor turn requires CURSOR_API_KEY before a model MCP tool-call",
    "evidence": "cursor-agent mcp list listed ac-verify; placement and uninstall clean passed"
  },
  {
    "host": "vscode-copilot",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "VS Code Copilot extension config; no local host CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local host CLI accept/runtime lane; workspace/user placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "jetbrains-copilot",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "JetBrains Copilot extension config; project-scope content",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local host CLI accept/runtime lane; project-scope adapter placement only",
    "evidence": "verify-host adapter-placement passed with preferred project scope: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "copilot-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "GitHub Copilot CLI 1.0.64 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_COPILOT_E2E_OK; MCP notepad_stats call observed; agent-plugin (Agent Plugins 1.0.0) SSOT bundle live-verified on GitHub Copilot CLI 1.0.80 macOS 2026-09-02: plugin marketplace add + plugin install + plugin list, installed tree keeps com.github.copilot/ + bin/agent-connector.mjs"
  },
  {
    "host": "gemini-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "gemini 0.42.0 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; Stop has no Gemini CLI hook equivalent; -y in an untrusted folder needs GEMINI_CLI_TRUST_WORKSPACE=true",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event) with a Gemini generateContent wire via GOOGLE_GEMINI_BASE_URL: gemini -y -p: mcp_acme-db_acme_query called -> probe logged tools/call; SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, SessionEnd fired through ~/.gemini/settings.json hooks"
  },
  {
    "host": "opencode",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "opencode 1.17.0 installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_OPENCODE_E2E_OK"
  },
  {
    "host": "mimo-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "mimo @mimo-ai/cli installed in .verify-tools",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): mimocode.json provider block (@ai-sdk/openai-compatible) + mimo run -m mock/mock-model: acme-db_acme_query called -> probe logged tools/call; UserPromptSubmit, SessionStart, PreToolUse, PostToolUse, Stop fired through the acme-db plugin"
  },
  {
    "host": "kilo",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Kilo IDE extension config; no local host CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "kilo binary belongs to kilo-cli adapter; Kilo IDE adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "kilo-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "kilo @kilocode/cli 7.5.15 installed in .verify-tools",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): kilo.jsonc provider block (@ai-sdk/openai-compatible) + kilo run -m mock/mock-model: acme-db_acme_query called -> probe logged tools/call; UserPromptSubmit, SessionStart, PreToolUse, PostToolUse, Stop fired through the acme-db plugin"
  },
  {
    "host": "warp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Warp terminal GUI host; no headless config verb",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local host CLI accept/runtime lane; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "hermes",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "hermes 0.20.4 (~/.hermes/hermes-agent venv, official installer)",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; UserPromptSubmit and Stop have no Hermes hook equivalent (adapter skips them visibly)",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): HERMES_HOME isolated; model.provider custom + base_url; hermes -z --yolo --accept-hooks: MCP tool exposed as deferred mcp__acme_db__acme_query behind tool_search/tool_describe/tool_call, model invoked it via tool_call -> probe logged tools/call; on_session_start, pre_tool_call, post_tool_call, on_session_end ran through the agent-connector binary"
  },
  {
    "host": "nemoclaw",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "NemoClaw adapter config; no verified standalone headless CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "npm nemoclaw 0.1.0 has no bin; adapter placement verified without installing wrong package",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "openclaw",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "openclaw 2026.9.2 npm CLI installed in .verify-tools",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; OpenClaw warns that the acme-db extension has an unverifiable origin but loads it",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): openclaw.json models.providers.mock (openai-completions) + agents.defaults.model.primary; openclaw agent --local --json: acme-db__acme_query called -> probe logged tools/call; PreToolUse, PostToolUse fired through the extension"
  },
  {
    "host": "zed",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Zed editor config host; GUI binary only",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "zed binary launches the GUI; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "antigravity",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Antigravity IDE config host",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "IDE surface; live CLI coverage is tracked under antigravity-cli",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "antigravity-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Antigravity CLI installed",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "OMAC_AGY_E2E_OK; MCP_TOOL notepad_stats observed in transcript"
  },
  {
    "host": "kiro",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Kiro IDE config host; no local headless CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local host CLI accept/runtime lane; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "qwen-code",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "qwen @qwen-code/qwen-code installed in .verify-tools",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; MCP tools are deferred behind tool_search, so the model fetches mcp__acme-db__acme_query before calling it",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): OPENAI_BASE_URL/OPENAI_MODEL env; qwen -y: model called tool_search then mcp__acme-db__acme_query -> probe logged tools/call; SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, Stop fired through ~/.qwen/settings.json hooks"
  },
  {
    "host": "kimi",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "kimi @moonshot-ai/kimi-code 0.41.0 installed in .verify-tools",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; kimi -p cannot be combined with --yolo, and top-level TOML keys must precede the [[hooks]] tables",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): config.toml [providers.mock] type openai + [models.mock] protocol openai + default_model; kimi -p: mcp__acme-db__acme_query called -> probe logged tools/call; SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, Stop fired via [[hooks]]"
  },
  {
    "host": "pi",
    "installProbe": "PASS_AFTER_FIX",
    "doctorProbe": "PASS",
    "hostCliSurface": "pi @earendil-works/pi-coding-agent installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "content-only host; no MCP or lifecycle-hook accept/runtime lane",
    "evidence": "official Pi CLI installed; content fixture prompts/skills/actions/memory placement+uninstall clean passed"
  },
  {
    "host": "omp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "omp 16.1.16 @oh-my-pi/pi-coding-agent installed globally",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; in omp -p print mode only SessionStart, PreToolUse and PostToolUse were observed (no UserPromptSubmit/Stop/SessionEnd before exit)",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): OMP_CODING_AGENT_DIR isolated; models.json custom openai-completions provider; omp -p --approval-mode yolo --model mock/mock-model: mcp__acme_db_acme_query called -> probe logged tools/call; SessionStart, PreToolUse, PostToolUse fired through the acme-db extension"
  },
  {
    "host": "droid",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "droid pinned Windows CLI installed in .verify-tools",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "Droid model turn is auth-gated before a model MCP tool-call",
    "evidence": "droid mcp list listed ac-verify; placement and uninstall clean passed"
  },
  {
    "host": "openhands",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "OpenHands adapter config; package exposes no usable local headless app here",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local headless host app exposed by current package; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "cline",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "cline 3.0.61 installed in .verify-tools",
    "headlessModelMcpE2e": "PARTIAL",
    "result": "INSTALL_DOCTOR_VERIFIED_CLI_READS_NO_MCP",
    "issueOrBlocker": "cline CLI model turn is reachable without account auth via cline auth openai -b <base url>, but the CLI tool set (read_files, run_commands, editor, submit_and_exit) exposes no MCP tools and it does not read the VS Code extension cline_mcp_settings.json the adapter writes",
    "evidence": "extension-path doctor passed; 2026-09-07 mock-provider lane: model requests reached the mock, no MCP tool offered, probe server never started"
  },
  {
    "host": "trae",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Trae editor config host; no local headless CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local host CLI accept/runtime lane; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "amp",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "amp 0.0.1782236573-g268fa2 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "amp requires login/API key before model call",
    "evidence": "amp mcp list shows oh-my-agent-connector server configured"
  },
  {
    "host": "codebuff",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "codebuff npm CLI installed in .verify-tools",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "no offline accept verb; mcp list is parsed as an agent prompt and needs auth/runtime boot",
    "evidence": "codebuff placement+uninstall clean passed"
  },
  {
    "host": "mux",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Mux desktop/browser config host; no local headless CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local host CLI accept/runtime lane; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "crush",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "crush @charmland/crush installed in .verify-tools",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): crush.json providers.mock (type openai) + models.large/small; crush run -q: mcp_acme-db_acme_query called -> probe logged tools/call; the single wired hook (PreToolUse) fired"
  },
  {
    "host": "goose",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "goose 1.49.0 installed via Homebrew block-goose-cli",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): config.yaml GOOSE_PROVIDER openai + OPENAI_HOST mock + GOOSE_MODE auto; goose run -q --no-session -t: acme-db__acme_query called -> probe logged tools/call; SessionStart, UserPromptSubmit, PreToolUse, PostToolUse, Stop, SessionEnd all fired via ~/.agents/plugins/acme-db/hooks/hooks.json"
  },
  {
    "host": "amazon-q",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Amazon Q CLI 1.19.7 installed",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "MCP_INSTALL_VERIFIED_AUTH_BLOCKED",
    "issueOrBlocker": "q requires login before mcp list/chat model call",
    "evidence": "q mcp list and q chat --no-interactive return login required"
  },
  {
    "host": "continue",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Continue @continuedev/cli (cn) installed in .verify-tools",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "the six config.yaml hooks did not fire in cn -p headless mode; hook lane not observed",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): config.yaml models[] (provider openai, apiBase mock) + cn -p --auto --config: acme_query called -> probe logged tools/call"
  },
  {
    "host": "windsurf",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Windsurf editor config host; no local headless CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "no local host CLI accept/runtime lane; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "grok-build",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "grok 1.0.0 official xAI binary (~/.grok/bin/grok)",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; Grok reaches MCP tools through its search_tool/use_tool meta-tools and PreToolUse did not fire for use_tool",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): GROK_HOME isolated; [model.mock] custom model (api_backend chat_completions) selected via [models].default; grok -p --yolo --output-format json: events.jsonl mcp_server_connected acme-db tools=[acme_query]; model called use_tool(tool_name acme-db__acme_query) -> probe logged tools/call; SessionStart, UserPromptSubmit, PostToolUse, Stop, SessionEnd fired through ~/.grok/hooks/agent-connector.json"
  },
  {
    "host": "grok-cli",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "grok-dev npm CLI installed in .verify-tools",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; PreToolUse/PostToolUse did not fire for the MCP tool call (SessionStart, UserPromptSubmit, Stop did)",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): grok -p -u <mock base url> -k -m mock-model: mcp_acme-db__acme_query called -> probe logged tools/call; SessionStart, UserPromptSubmit, Stop fired through ~/.grok/user-settings.json hooks"
  },
  {
    "host": "devin",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "Devin remote/service adapter; no local headless CLI",
    "headlessModelMcpE2e": "NOT_RUN",
    "result": "ADAPTER_PLACEMENT_VERIFIED",
    "issueOrBlocker": "remote/service-oriented host; adapter placement only",
    "evidence": "verify-host adapter-placement passed: isolated install wrote connector id and uninstall removed it"
  },
  {
    "host": "open-interpreter",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "interpreter 0.0.41 (Rust Codex fork) installed via the official install script",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none; with approvals=\"never\" the server table needs default_tools_approval_mode = \"approve\" or the MCP call is denied (interactive runs prompt instead); PreToolUse fires for exec_command but not for MCP tools",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): interpreter exec --dangerously-bypass-hook-trust called mcp__acme_db_acme_query -> probe logged tools/call acme_query; hooks SessionStart, UserPromptSubmit, PostToolUse (tool=mcp__acme_db__acme_query), Stop, SessionEnd ran through ~/.openinterpreter/hooks.json"
  },
  {
    "host": "junie",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "junie @jetbrains/junie CLI 26.8.31 (3013.7) installed in .verify-tools",
    "headlessModelMcpE2e": "BLOCKED",
    "result": "INSTALL_DOCTOR_VERIFIED_NO_HEADLESS_MODE",
    "issueOrBlocker": "junie --task --provider litellm reached startup but hung on a macOS Keychain availability check (MacOSKeychainStorage) before any model call; Junie resolves its home via Java user.home so $HOME isolation does not apply",
    "evidence": "junie placement+uninstall clean passed; 2026-09-07 headless attempt against a local LiteLLM-shaped mock produced no model request"
  },
  {
    "host": "mistral-vibe",
    "installProbe": "PASS",
    "doctorProbe": "PASS",
    "hostCliSurface": "vibe 2.25.0 installed via uv tool install mistral-vibe",
    "headlessModelMcpE2e": "PASS",
    "result": "VERIFIED_E2E",
    "issueOrBlocker": "none (mcp-only host, no hooks expected)",
    "evidence": "2026-09-07 local mock OpenAI-compatible provider lane (no API key, isolated HOME, agent-connector install of a probe connector whose stdio MCP server logs every tools/call and whose SDK hooks log every event): config.toml [[providers]] backend generic + [[models]] + active_model; vibe -p --yolo: acme-db_acme_query called -> probe logged tools/call"
  }
] as const satisfies readonly HostVerificationResult[];

export const hostVerificationCount = hostVerificationResults.length;
