/**
 * release-status.generated — generated by scripts/generate-site-release-status.mjs.
 *
 * Do not edit by hand. Live registry/API lookups are best-effort; failed remote
 * reads keep the previous snapshot while local package/workflow facts refresh.
 */

export interface ReleaseWorkflowStatus {
  present: boolean;
  path: string;
  url: string;
}

export interface ReleaseStatus {
  packageName: string;
  localVersion: string;
  npmLatest: string | null;
  npmPublishedAt: string | null;
  npmPackageUrl: string;
  npmFetchStatus: string;
  githubLatest: string | null;
  githubReleaseUrl: string;
  githubPublishedAt: string | null;
  githubFetchStatus: string;
  repoUrl: string;
  githubActionsUrl: string;
  ciWorkflow: ReleaseWorkflowStatus;
  deployWorkflow: ReleaseWorkflowStatus;
  releaseWorkflow: ReleaseWorkflowStatus;
}

export const releaseStatus = {
  "packageName": "@ken-jo/agent-connector",
  "localVersion": "0.6.4",
  "npmLatest": "0.6.4",
  "npmPublishedAt": "2026-09-05T14:00:11.849Z",
  "npmPackageUrl": "https://www.npmjs.com/package/@ken-jo/agent-connector",
  "npmFetchStatus": "ok",
  "githubLatest": "v0.6.4",
  "githubReleaseUrl": "https://github.com/ken-jo/agent-connector/releases/tag/v0.6.4",
  "githubPublishedAt": "2026-09-05T14:00:15Z",
  "githubFetchStatus": "ok",
  "repoUrl": "https://github.com/ken-jo/agent-connector",
  "githubActionsUrl": "https://github.com/ken-jo/agent-connector/actions",
  "ciWorkflow": {
    "present": true,
    "path": ".github/workflows/ci.yml",
    "url": "https://github.com/ken-jo/agent-connector/actions/workflows/ci.yml"
  },
  "deployWorkflow": {
    "present": true,
    "path": ".github/workflows/deploy-site.yml",
    "url": "https://github.com/ken-jo/agent-connector/actions/workflows/deploy-site.yml"
  },
  "releaseWorkflow": {
    "present": true,
    "path": ".github/workflows/release.yml",
    "url": "https://github.com/ken-jo/agent-connector/actions/workflows/release.yml"
  }
} as const satisfies ReleaseStatus;
