/**
 * core/package-formats/npm — the `npm-plugin` emitter (opencode + kilo-cli + pi).
 *
 * This is the one genuinely NET-NEW artifact: a publishable npm package whose
 * default export is a plugin module. It is emitted ONLY in its clean form — a
 * real package.json + an ESM `index.js` bridge — never a
 * half-baked stub. The surface limit (documented, and returned as notes) is
 * inherent to the opencode/kilo plugin contract: ONLY hook code rides inside the
 * npm package; commands/skills/subagents are native host dirs and MCP is a
 * config key, so they do NOT ride inside the published module.
 *
 * Layout:
 *   <outDir>/<id>/
 *   ├── package.json   (type:module, exports ".", keywords incl. "opencode-plugin"
 *   │                   + "pi-package", engines.node)
 *   ├── index.js       (default-export plugin fn; bridges each declared hook event
 *   │                   to `<homeBin> hook opencode <event> --connector <id>`)
 *   ├── skills/<n>/SKILL.md  (pi packages DO bundle skills; opencode ignores them)
 *   └── README.md
 *
 * The bridge shells out to the framework runtime bundled as this plugin's npm
 * dependency, then falls back to a PATH `agent-connector` binary for hand-built
 * bundles. The SAME universal json-stdio dispatcher every other host uses serves
 * the npm host too. (MCP wrapping is NOT inlined here: opencode's MCP is the
 * opencode.json "mcp" key, out of band for the npm package; a note records this.)
 */

import { createRequire } from "node:module";
import { join } from "node:path";

import type { HookEventName, ResolvedConnector } from "../types.js";
import { renderSkillMd } from "../../adapters/claude-code/render.js";
import {
  createEmitter,
  json,
  resolveWithin,
  type EmitContext,
  type FormatEmitter,
  type PackageResult,
} from "./shared.js";

const AGENT_CONNECTOR_PACKAGE_NAME = "@ken-jo/agent-connector";

/** OpenCode event keys this connector can bridge (PreToolUse/PostToolUse/SessionStart). */
const EVENT_TO_OPENCODE: Partial<Record<HookEventName, string>> = {
  PreToolUse: "tool.execute.before",
  PostToolUse: "tool.execute.after",
  SessionStart: "experimental.chat.system.transform",
};

function resolveFrameworkDependencyRange(): string {
  const req = createRequire(import.meta.url);
  for (const rel of ["../../../package.json", "../../package.json", "../package.json"]) {
    try {
      const pkg = req(rel) as { name?: string; version?: string };
      if (
        pkg.name === AGENT_CONNECTOR_PACKAGE_NAME &&
        typeof pkg.version === "string" &&
        /^\d+\.\d+\.\d+/.test(pkg.version)
      ) {
        return `^${pkg.version}`;
      }
    } catch {
      /* keep walking */
    }
  }
  return "*";
}

/** Build the publishable package.json for an opencode/kilo/pi plugin package. */
function buildPackageJson(connector: ResolvedConnector): Record<string, unknown> {
  // Use an opencode- name prefix (the discovery-confirmed convention) so the
  // package is discoverable; keywords cover opencode + pi-package.
  const pkgName = connector.id.startsWith("opencode-")
    ? connector.id
    : `opencode-${connector.id}`;
  const version =
    connector.version && connector.version !== "0.0.0" ? connector.version : "0.0.1";
  const pkg: Record<string, unknown> = {
    name: pkgName,
    version,
    description: `${connector.displayName} — connector emitted by agent-connector`,
    type: "module",
    main: "index.js",
    exports: { ".": "./index.js" },
    keywords: ["opencode", "opencode-plugin", "pi-package", "agent-connector"],
    dependencies: { [AGENT_CONNECTOR_PACKAGE_NAME]: resolveFrameworkDependencyRange() },
    // pi reads skills/prompts/themes/extensions from the package.json "pi" key.
    pi: { extensions: ["./index.js"], skills: ["./skills"] },
    engines: { node: ">=18.17", opencode: ">=1.0.0" },
    // NOTE: no hardcoded license — this is the DEVELOPER'S publishable package
    // and agent-connector has no authority to license it. The emitter returns a
    // note telling the dev to set license (and author) before `npm publish`.
  };
  if (connector.publish?.author?.name) {
    pkg.author = connector.publish.author.name;
  }
  return pkg;
}

/** Compose the self-contained ESM plugin bridge (default-export plugin fn). */
function buildIndexJs(connector: ResolvedConnector): string {
  const frameworkPackageName = JSON.stringify(AGENT_CONNECTOR_PACKAGE_NAME);
  const connectorId = JSON.stringify(connector.id);

  const events = connector.hookEvents.filter(
    (e): e is HookEventName => EVENT_TO_OPENCODE[e] !== undefined,
  );
  const has = (e: HookEventName): boolean => events.includes(e);

  const header = `/**
 * AUTO-GENERATED by agent-connector — DO NOT EDIT.
 *
 * Publishable OpenCode/Kilo/Pi plugin for connector ${connector.id}. It imports
 * no public framework APIs: every hook invocation shells out to the bundled
 * framework runtime's universal entrypoint and JSON-parses the normalized response.
 * Fail-open: any bridge error degrades to "allow".
 */
import { execFileSync, execSync } from "node:child_process";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const FRAMEWORK_PACKAGE_NAME = ${frameworkPackageName};
const CONNECTOR_ID = ${connectorId};
const require = createRequire(import.meta.url);

function resolveBridgeCommand() {
  try {
    const pkgJson = require.resolve(FRAMEWORK_PACKAGE_NAME + "/package.json");
    return { command: process.execPath, prefix: [join(dirname(pkgJson), "dist", "cli.js")] };
  } catch {
    return { command: "agent-connector", prefix: [] };
  }
}

const BRIDGE_COMMAND = resolveBridgeCommand();

function bridge(event, payload) {
  try {
    // Prefer the runtime bundled as this plugin's dependency. The bare
    // agent-connector command is only a recovery fallback for hand-built bundles.
    const args = [...BRIDGE_COMMAND.prefix, "hook", "opencode", event, "--connector", CONNECTOR_ID];
    const opts = { input: JSON.stringify(payload), encoding: "utf8" };
    const stdout =
      process.platform === "win32" && BRIDGE_COMMAND.command === "agent-connector"
        ? execSync([BRIDGE_COMMAND.command, ...args].map((a) => '"' + a + '"').join(" "), opts)
        : execFileSync(BRIDGE_COMMAND.command, args, opts);
    const text = (stdout || "").trim();
    if (text === "") return { decision: "allow" };
    return JSON.parse(text);
  } catch {
    return null;
  }
}
`;

  const handlers: string[] = [];
  if (has("PreToolUse")) {
    handlers.push(`    "tool.execute.before": async (input, output) => {
      const res = bridge("PreToolUse", {
        toolName: input.tool ?? "",
        toolInput: (output && output.args) ?? {},
        sessionId: input.sessionID ?? "",
        projectDir: PROJECT_DIR,
      });
      if (!res) return;
      if (res.decision === "deny" || res.decision === "ask") {
        throw new Error(res.reason || "Blocked by ${connector.id}");
      }
      if (res.updatedInput && output && output.args) Object.assign(output.args, res.updatedInput);
    },`);
  }
  if (has("PostToolUse")) {
    handlers.push(`    "tool.execute.after": async (input, output) => {
      const res = bridge("PostToolUse", {
        toolName: input.tool ?? "",
        toolInput: input.args ?? {},
        toolOutput: output ? output.output : undefined,
        sessionId: input.sessionID ?? "",
        projectDir: PROJECT_DIR,
      });
      if (!res) return;
      if (typeof res.updatedOutput === "string" && output) output.output = res.updatedOutput;
    },`);
  }
  if (has("SessionStart")) {
    handlers.push(`    "experimental.chat.system.transform": async (input, output) => {
      const res = bridge("SessionStart", {
        sessionId: (input && input.sessionID) ?? "",
        projectDir: PROJECT_DIR,
      });
      if (!res) return;
      if (res.additionalContext && output && Array.isArray(output.system)) {
        output.system.splice(1, 0, res.additionalContext);
      }
    },`);
  }

  const factory = `
export default async function (ctx) {
  const PROJECT_DIR =
    (ctx && (ctx.directory || (ctx.worktree && ctx.worktree.path))) || process.cwd();
  return {
${handlers.join("\n")}
  };
}
`;
  return header + factory;
}

export const emitNpmPlugin: FormatEmitter = (
  connector: ResolvedConnector,
  ctx: EmitContext,
): PackageResult => {
  const { emit, files } = createEmitter(ctx.dryRun);
  const pluginDir = join(ctx.outDir, connector.id);
  const notes: string[] = [];

  // ── package.json (publishable) ────────────────────────────────────────────
  emit(join(pluginDir, "package.json"), json(buildPackageJson(connector)));

  // ── index.js (the default-export plugin bridge) ───────────────────────────
  emit(join(pluginDir, "index.js"), buildIndexJs(connector));

  // ── skills/<name>/SKILL.md (+ resources) — pi bundles skills ──────────────
  for (const skill of connector.skills) {
    const skillDir = join(pluginDir, "skills", skill.name);
    emit(join(skillDir, "SKILL.md"), renderSkillMd(skill));
    for (const [rel, contents] of Object.entries(skill.resources ?? {})) {
      const target = resolveWithin(skillDir, rel);
      if (target === null) continue;
      emit(target, contents);
    }
  }

  // ── README.md ─────────────────────────────────────────────────────────────
  emit(
    join(pluginDir, "README.md"),
    `# ${connector.displayName}\n\nOpenCode / Kilo / Pi plugin package emitted by agent-connector.\n\n` +
      "Install with `opencode plugin install <pkg>` / `kilo plugin <pkg>` / `pi install <pkg>`.\n\n" +
      "Local install (no npm publish needed — live-verified on opencode 1.17.0 / kilo 7.3.16):\n" +
      "`opencode plugin --global file:///<abs-dir>` or `kilo plugin --global file:///<abs-dir>`\n" +
      "(bare absolute paths work too; the entry lands in the config `plugin` array —\n" +
      "there is no uninstall verb, remove it by editing that array).\n\n" +
      "## Prerequisite\n\n" +
      "The generated package depends on `@ken-jo/agent-connector` and hooks resolve that\n" +
      "local runtime first. A global `agent-connector` binary is only a recovery fallback\n" +
      "for hand-built bundles; hooks silently no-op, fail-open, if neither runtime exists.\n\n" +
      "## Before you publish\n\n" +
      "The emitted package.json carries **no `license` and no `author`** unless your\n" +
      "connector declared `publish.author` — set them to YOUR terms before `npm publish`.\n",
  );

  notes.push(
    "npm-plugin: hooks resolve the bundled @ken-jo/agent-connector dependency first; a global agent-connector binary is only a recovery fallback, and hooks silently fail-open without either runtime",
  );
  notes.push(
    "npm-plugin: set license/author in the emitted package.json before `npm publish` — agent-connector does not license your plugin for you",
  );

  // Surface the inherent limits of the npm-plugin contract.
  if (connector.commands.length > 0) {
    notes.push(
      `npm-plugin: ${connector.commands.length} command(s) NOT bundled — opencode/kilo commands are native host dirs`,
    );
  }
  if (connector.subagents.length > 0) {
    notes.push(
      `npm-plugin: ${connector.subagents.length} subagent(s) NOT bundled — opencode/kilo subagents are native host dirs`,
    );
  }
  if (connector.server) {
    notes.push(
      `npm-plugin: MCP server NOT bundled inside the package — register it via the opencode.json "mcp" key`,
    );
  }

  return { files, pluginDir, ...(notes.length > 0 ? { notes } : {}) };
};
