/**
 * core/package-formats/npm — the `npm-plugin` emitter (opencode + kilo-cli + pi).
 *
 * This is the one genuinely NET-NEW artifact: a publishable npm package whose
 * default export is a plugin module. It is emitted ONLY in its clean form — a
 * real package.json + a self-contained ESM `index.js` bridge — never a
 * half-baked stub. The surface limit (documented, and returned as notes) is
 * inherent to the opencode/kilo plugin contract: ONLY hook code rides inside the
 * npm package; commands/skills/subagents are native host dirs and MCP is a
 * config key, so they do NOT ride inside the published module.
 *
 * Layout:
 *   <outDir>/<id>/
 *   ├── package.json   (type:module, exports ".", keywords incl. "opencode-plugin"
 *   │                   + "pi-package", engines.node)
 *   ├── index.js       (default-export plugin fn; bridges each declared hook event
 *   │                   to `<homeBin> hook opencode <event> --connector <id>`)
 *   ├── skills/<n>/SKILL.md  (pi packages DO bundle skills; opencode ignores them)
 *   └── README.md
 *
 * The bridge shells out to the ONE stable home binary over child_process, so the
 * SAME universal json-stdio dispatcher every other host uses serves the npm host
 * too — and telemetry continues to flow through the home-bin. (MCP wrapping is
 * NOT inlined here: opencode's MCP is the opencode.json "mcp" key, out of band
 * for the npm package; a note records this.)
 */

import { join } from "node:path";

import type { HookEventName, ResolvedConnector } from "../types.js";
import { renderSkillMd } from "../../adapters/claude-code/render.js";
import {
  createEmitter,
  json,
  resolveWithin,
  type EmitContext,
  type FormatEmitter,
  type PackageResult,
} from "./shared.js";

/** OpenCode event keys this connector can bridge (PreToolUse/PostToolUse/SessionStart). */
const EVENT_TO_OPENCODE: Partial<Record<HookEventName, string>> = {
  PreToolUse: "tool.execute.before",
  PostToolUse: "tool.execute.after",
  SessionStart: "experimental.chat.system.transform",
};

/** Build the publishable package.json for an opencode/kilo/pi plugin package. */
function buildPackageJson(connector: ResolvedConnector): Record<string, unknown> {
  // Use an opencode- name prefix (the discovery-confirmed convention) so the
  // package is discoverable; keywords cover opencode + pi-package.
  const pkgName = connector.id.startsWith("opencode-")
    ? connector.id
    : `opencode-${connector.id}`;
  const version =
    connector.version && connector.version !== "0.0.0" ? connector.version : "0.0.1";
  const pkg: Record<string, unknown> = {
    name: pkgName,
    version,
    description: `${connector.displayName} — connector emitted by agent-connector`,
    type: "module",
    main: "index.js",
    exports: { ".": "./index.js" },
    keywords: ["opencode", "opencode-plugin", "pi-package", "agent-connector"],
    // pi reads skills/prompts/themes/extensions from the package.json "pi" key.
    pi: { extensions: ["./index.js"], skills: ["./skills"] },
    engines: { node: ">=18.17", opencode: ">=1.0.0" },
    // NOTE: no hardcoded license — this is the DEVELOPER'S publishable package
    // and agent-connector has no authority to license it. The emitter returns a
    // note telling the dev to set license (and author) before `npm publish`.
  };
  if (connector.publish?.author?.name) {
    pkg.author = connector.publish.author.name;
  }
  return pkg;
}

/** Compose the self-contained ESM plugin bridge (default-export plugin fn). */
function buildIndexJs(connector: ResolvedConnector): string {
  const homeBin = JSON.stringify("agent-connector");
  const connectorId = JSON.stringify(connector.id);

  const events = connector.hookEvents.filter(
    (e): e is HookEventName => EVENT_TO_OPENCODE[e] !== undefined,
  );
  const has = (e: HookEventName): boolean => events.includes(e);

  const header = `/**
 * AUTO-GENERATED by agent-connector — DO NOT EDIT.
 *
 * Publishable OpenCode/Kilo/Pi plugin for connector ${connector.id}. It imports
 * nothing from agent-connector: every hook invocation shells out to the stable
 * home binary's universal entrypoint and JSON-parses the normalized response.
 * Fail-open: any bridge error degrades to "allow".
 */
import { execFileSync, execSync } from "node:child_process";

const HOME_BIN = ${homeBin};
const CONNECTOR_ID = ${connectorId};

function bridge(event, payload) {
  try {
    // The published bridge resolves HOME_BIN by bare name via the consumer's
    // PATH, where on Windows it is agent-connector.cmd. Node cannot execFile a
    // .cmd, and shell+args is deprecated (DEP0190), so on Windows run one quoted
    // command line via a shell (cmd.exe applies PATHEXT). POSIX keeps execFile.
    const args = ["hook", "opencode", event, "--connector", CONNECTOR_ID];
    const opts = { input: JSON.stringify(payload), encoding: "utf8" };
    const stdout =
      process.platform === "win32"
        ? execSync([HOME_BIN, ...args].map((a) => '"' + a + '"').join(" "), opts)
        : execFileSync(HOME_BIN, args, opts);
    const text = (stdout || "").trim();
    if (text === "") return { decision: "allow" };
    return JSON.parse(text);
  } catch {
    return null;
  }
}
`;

  const handlers: string[] = [];
  if (has("PreToolUse")) {
    handlers.push(`    "tool.execute.before": async (input, output) => {
      const res = bridge("PreToolUse", {
        toolName: input.tool ?? "",
        toolInput: (output && output.args) ?? {},
        sessionId: input.sessionID ?? "",
        projectDir: PROJECT_DIR,
      });
      if (!res) return;
      if (res.decision === "deny" || res.decision === "ask") {
        throw new Error(res.reason || "Blocked by ${connector.id}");
      }
      if (res.updatedInput && output && output.args) Object.assign(output.args, res.updatedInput);
    },`);
  }
  if (has("PostToolUse")) {
    handlers.push(`    "tool.execute.after": async (input, output) => {
      const res = bridge("PostToolUse", {
        toolName: input.tool ?? "",
        toolInput: input.args ?? {},
        toolOutput: output ? output.output : undefined,
        sessionId: input.sessionID ?? "",
        projectDir: PROJECT_DIR,
      });
      if (!res) return;
      if (typeof res.updatedOutput === "string" && output) output.output = res.updatedOutput;
    },`);
  }
  if (has("SessionStart")) {
    handlers.push(`    "experimental.chat.system.transform": async (input, output) => {
      const res = bridge("SessionStart", {
        sessionId: (input && input.sessionID) ?? "",
        projectDir: PROJECT_DIR,
      });
      if (!res) return;
      if (res.additionalContext && output && Array.isArray(output.system)) {
        output.system.splice(1, 0, res.additionalContext);
      }
    },`);
  }

  const factory = `
export default async function (ctx) {
  const PROJECT_DIR =
    (ctx && (ctx.directory || (ctx.worktree && ctx.worktree.path))) || process.cwd();
  return {
${handlers.join("\n")}
  };
}
`;
  return header + factory;
}

export const emitNpmPlugin: FormatEmitter = (
  connector: ResolvedConnector,
  ctx: EmitContext,
): PackageResult => {
  const { emit, files } = createEmitter(ctx.dryRun);
  const pluginDir = join(ctx.outDir, connector.id);
  const notes: string[] = [];

  // ── package.json (publishable) ────────────────────────────────────────────
  emit(join(pluginDir, "package.json"), json(buildPackageJson(connector)));

  // ── index.js (the default-export plugin bridge) ───────────────────────────
  emit(join(pluginDir, "index.js"), buildIndexJs(connector));

  // ── skills/<name>/SKILL.md (+ resources) — pi bundles skills ──────────────
  for (const skill of connector.skills) {
    const skillDir = join(pluginDir, "skills", skill.name);
    emit(join(skillDir, "SKILL.md"), renderSkillMd(skill));
    for (const [rel, contents] of Object.entries(skill.resources ?? {})) {
      const target = resolveWithin(skillDir, rel);
      if (target === null) continue;
      emit(target, contents);
    }
  }

  // ── README.md ─────────────────────────────────────────────────────────────
  emit(
    join(pluginDir, "README.md"),
    `# ${connector.displayName}\n\nOpenCode / Kilo / Pi plugin package emitted by agent-connector.\n\n` +
      "Install with `opencode plugin install <pkg>` / `kilo plugin <pkg>` / `pi install <pkg>`.\n\n" +
      "## Prerequisite\n\n" +
      "Hooks shell out to the `agent-connector` CLI resolved from the consumer's PATH —\n" +
      "the consumer machine needs `npm i -g @ken-jo/agent-connector` (hooks silently no-op,\n" +
      "fail-open, without it).\n\n" +
      "## Before you publish\n\n" +
      "The emitted package.json carries **no `license` and no `author`** unless your\n" +
      "connector declared `publish.author` — set them to YOUR terms before `npm publish`.\n",
  );

  // The published bridge resolves the CLI by bare name on the consumer's PATH.
  notes.push(
    "npm-plugin: hooks require `npm i -g @ken-jo/agent-connector` on the consumer machine (bridge resolves the CLI by name on PATH; silently fail-open without it)",
  );
  notes.push(
    "npm-plugin: set license/author in the emitted package.json before `npm publish` — agent-connector does not license your plugin for you",
  );

  // Surface the inherent limits of the npm-plugin contract.
  if (connector.commands.length > 0) {
    notes.push(
      `npm-plugin: ${connector.commands.length} command(s) NOT bundled — opencode/kilo commands are native host dirs`,
    );
  }
  if (connector.subagents.length > 0) {
    notes.push(
      `npm-plugin: ${connector.subagents.length} subagent(s) NOT bundled — opencode/kilo subagents are native host dirs`,
    );
  }
  if (connector.server) {
    notes.push(
      `npm-plugin: MCP server NOT bundled inside the package — register it via the opencode.json "mcp" key`,
    );
  }

  return { files, pluginDir, ...(notes.length > 0 ? { notes } : {}) };
};
